### ISSUE TITLE
I can't run the Example.go 

### ISSUE THREAD

**Issue by stevef1uk** [global-soft-ba/decisionTable#5]
Sorry, been a while since I last used Go. I tried changing the package to main so I could run the Example.go but then I found
Example.go:49:14: undefined: CreateDecisionTable

Then I became stuck as even after using the replace in go.mod to allow me to reorganise the code base I still couldn't figure out how to rn this Example.

**Comment by stevef1uk** [comment]
Sorry worked out how to fix this locally, although it still doesn't run properly ;-)

**Comment by mmlinarevic** [comment]
Hey @stevef1uk, sorry for the inconvenience, ReadMe and Example.go was not updated to the latest version that supports OMG standard grammar. Should be sorted out now. 
The lib is still a work in progress, I guess that you had problems with DateAndTime expressions which are currently being implemented, so I have removed those from Example.go until it is finished.

**Comment by stevef1uk** [comment]
Many thanks that now runs successfully :-)
